# Generated by Django 5.0.7 on 2024-08-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='', upload_to='upload/ads1/')),
            ],
        ),
        migrations.CreateModel(
            name='Advertising2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='', upload_to='upload/ads2/')),
            ],
        ),
    ]
