# Generated by Django 5.0.7 on 2024-08-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Title',
            field=models.CharField(max_length=70),
        ),
    ]
