# Generated by Django 5.0.7 on 2024-08-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(max_length=20, verbose_name='تام'),
        ),
    ]
