# Generated by Django 5.0.7 on 2024-08-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Ename',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
