# Generated by Django 5.0.7 on 2024-08-19 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_product_ename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Price', models.IntegerField(default=0)),
                ('Offer', models.BooleanField(default=False)),
                ('OfferPrice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Garanti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Month', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Bime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.bime'),
        ),
    ]
