# Generated by Django 5.0.7 on 2024-08-19 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_bime_garanti_product_bime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Bime',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.bime'),
        ),
    ]
