# Generated by Django 5.0.7 on 2024-08-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_product_bime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Bime',
        ),
    ]
