# Generated by Django 5.0.7 on 2024-08-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_product_ename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bime',
        ),
        migrations.DeleteModel(
            name='Garanti',
        ),
    ]
