# Generated by Django 5.0.7 on 2024-08-19 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_product_bime_alter_product_garanti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Bime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.bime'),
        ),
    ]
