# Generated by Django 5.0.7 on 2024-08-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_product_bime_remove_product_garanti_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Price', models.IntegerField(default=0)),
                ('Offer', models.BooleanField(default=False)),
                ('OfferPrice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Garanti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20)),
                ('Month', models.IntegerField(default=1)),
            ],
        ),
    ]
