# Generated by Django 5.0.7 on 2024-08-19 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_bime_garanti'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Garanti',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.garanti'),
        ),
    ]
