# Generated by Django 5.0.7 on 2024-08-19 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_product_en_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Star',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
