# Generated by Django 5.0.7 on 2024-08-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_product_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='City',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Owner_Product',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
