# Generated by Django 5.0.7 on 2024-08-19 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_product_city_product_owner_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Owner_Product',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.owner_product'),
        ),
    ]
