# Generated by Django 5.0.7 on 2024-08-19 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_owner_product_alter_product_owner_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='bime',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
