# Generated by Django 5.0.7 on 2024-08-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_color_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_product',
            name='Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
