# Generated by Django 5.0.7 on 2024-08-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_alter_owner_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_product',
            name='Name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
