# Generated by Django 5.0.7 on 2024-08-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_owner_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
