# Generated by Django 5.0.7 on 2024-08-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_color_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='HexColor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
