# Generated by Django 5.0.7 on 2024-08-19 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_remove_product_color_color1_product_color1_color2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Color1',
        ),
        migrations.RemoveField(
            model_name='color2',
            name='Color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Color2',
        ),
        migrations.RemoveField(
            model_name='color3',
            name='Color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Color3',
        ),
        migrations.RemoveField(
            model_name='color4',
            name='Color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Color4',
        ),
        migrations.AddField(
            model_name='product',
            name='Color',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.color'),
        ),
        migrations.DeleteModel(
            name='Color1',
        ),
        migrations.DeleteModel(
            name='Color2',
        ),
        migrations.DeleteModel(
            name='Color3',
        ),
        migrations.DeleteModel(
            name='Color4',
        ),
    ]
