# Generated by Django 5.0.7 on 2024-08-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Img1',
            field=models.ImageField(blank=True, null=True, upload_to='upload/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Img2',
            field=models.ImageField(blank=True, null=True, upload_to='upload/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Img3',
            field=models.ImageField(blank=True, null=True, upload_to='upload/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Img4',
            field=models.ImageField(blank=True, null=True, upload_to='upload/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Img5',
            field=models.ImageField(blank=True, null=True, upload_to='upload/products/'),
        ),
    ]
