# Generated by Django 5.0.7 on 2024-08-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_alter_product_img1_alter_product_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Freesend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Send_Price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
