# Generated by Django 5.0.7 on 2024-08-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_product_freesend_product_send_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Freesend',
            new_name='send',
        ),
    ]
