# Generated by Django 5.0.7 on 2024-08-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_rename_freesend_product_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bime',
            name='Category',
        ),
    ]
