# Generated by Django 5.0.7 on 2024-08-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_remove_bime_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Img1',
            field=models.ImageField(upload_to='upload/products/'),
        ),
    ]
