# Generated by Django 5.0.7 on 2024-08-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_alter_product_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='En_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
