# Generated by Django 5.0.7 on 2024-08-21 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_alter_product_en_name_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Color2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Color3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Color4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Color5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Img2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Img3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Img4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Img5',
        ),
        migrations.AddField(
            model_name='color',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
