# Generated by Django 5.0.7 on 2024-08-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_remove_product_color_remove_product_color2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='product',
            new_name='Product',
        ),
    ]
